import * as sessApi from "~/helpers/cacheSession-utils";
import { CACHE_SESSIONNAMES} from "~/helpers/constants";

const master_validate_default = {
    "dial_institution_master":{
        "code":{"length":10},
        "ccorporation_name":{"length":40},
        "medical_institution_name":{"length":40},
        "medical_institution_name_kana":{"length":40},
        "view_name":{"length":40},
        "representative_name":{"length":40},
        "doctor_name":{"length":40},
        "zip_code":{"length":40},
        "address_1":{"length":40},
        "address_2":{"length":40},
        "phone_number":{"length":15},
        "fax_number":{"length":15},
        "number_of_consoles":{"length":40},
        "prefectures_number":{"length":2},
        "point_table_number":{"length":40},
        "medical_institution_code":{"length":40},
        "treatment_type_code":{"length":40}
    },
    "bed_master":{
        "name":{
          "is_required":1,
          "length":10,
          "requierd_message":"ベッド番号を入力してください。",
          "overflow_message":"ベット番号を10文字以下で入力してください。",
          "type_error_message":""
        },
        "group_1":{
          "is_required":1,
          "length":32,
          "requierd_message":"グループ１を入力してください。",
          "overflow_message":"グループ１を32文字以下で入力してください。",
          "type_error_message":""
        },
        "group_2":{
          "is_required":1,
          "length":32,
          "requierd_message":"グループ2を入力してください。",
          "overflow_message":"グループ2を32文字以下で入力してください。",
          "type_error_message":""
        }
    },
    "dial_common_code_master":{
        "category":{"length":10},
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_material_master__anticoagulation":{
        "code":{"length":10},
        "name":{"length":35},
        "name_kana":{"length":35},
        "name_short":{"length":35},
        "unit":{"length":10}
    },
    "dial_material_master__anticoagulation_pattern":{
        "code":{"length":10},
        "name":{"length":35},
        "name_kana":{"length":35},
        "name_short":{"length":35}
    },
    "dial_material_master__common":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_material_master__console":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_material_master__dialysis_method":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "mode_number":{"length":10}
    },
    "dial_material_master__dialyzer":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "jan_code":{"length":20},
        "membrane_area":{"length":20},
        "cl":{"length":20},
        "blood_flow_rate":{"length":20},
        "dialysate_flow_rate":{"length":20},
        "efficiency":{"length":20},
        "flow_rate_ratio":{"length":20},
        "k":{"length":20}
    },
    "dial_periodic_examination_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "examination_category":{"length":20},
        "schedule_icon_text":{"length":20}
    },
    "dial_medicine_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "unit":{"length":10},
        "mhlw_code":{"length":10},
        "name_view":{"length":20},
        "generic_name":{"length":20},
        "medicinal_properties":{"length":30}
    },
    "dial_medicine_usage_group_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20}
    },
    "dial_medicine_usage_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_injection_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "unit":{"length":10},
        "mhlw_code":{"length":10},
        "name_view":{"length":20},
        "generic_name":{"length":20},
        "medicinal_properties":{"length":30},
        "one_unit_value":{"length":10}
    },
    "dial_mhlw_medicine_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "unit":{"length":10},
        "mhlw_code":{"length":10}
    },
    "dial_examination_master":{
        "code":{"length":10},
        "company_examination_code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20},
        "unit":{"length":20}
    },
    "dial_examination_master_pattern":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20}
    },
    "dial_disease_name_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_fee_management_master":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_holiday_master":{
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_other_facilities_master":{
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_other_facilities_master_department":{
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_other_facilities_master_doctor":{
        "name":{"length":20},
        "name_kana":{"length":20},
        "name_short":{"length":20}
    },
    "dial_prescription_set_master":{
        "name":{"length":20},
        "set_id":{"length":20}
    },
    "dial_injection_set_category":{
        "code":{"length":10},
        "name":{"length":20},
        "name_kana":{"length":20}
    },
    "dial_injection_set":{
        "name":{"length":20},
        "name_kana":{"length":20}
    },
    "dial_terminal_master":{
        "ip_addr":{"length":15}
    },
    "staff":{
        "name":{"length":20},
        "name_kana":{"length":20},
        "signin_id":{"length":20}
    },
    "dial_word_pattern":{
        "name":{"length":20},
        "name_kana":{"length":20}
    },
    "dial_word":{
        "word":{"length":20},
        "word_kana":{"length":20}
    }
}

export default function () {
    let init_status = sessApi.getObject(CACHE_SESSIONNAMES.INIT_STATUS);
    let dial_master_validate = init_status.dial_master_validate;
    let return_obj = master_validate_default;
    if(dial_master_validate !== undefined || dial_master_validate != null && Object.keys(dial_master_validate).length > 0)
    Object.keys(dial_master_validate).map(index=>{
        return_obj[index] = dial_master_validate[index];
    });
    return return_obj;
}