import * as sessApi from "~/helpers/cacheSession-utils";
import { CACHE_SESSIONNAMES} from "~/helpers/constants";

const patient_validate_default = {
  "dial_master_patient":{
    "patient_name":{
        "is_required":1,
        "length":20,
        "requierd_message":"患者氏名を入力してください。",
        "overflow_message":"患者氏名は20文字以下で入力してください。",
        "type_error_message":""
    },
    "patient_kana_name":{
        "is_required":1,
        "length":20,
        "requierd_message":"カナ氏名を入力してください。",
        "overflow_message":"カナ氏名は20文字以下で入力してください。",
        "type_error_message":""
    },
    "birthday":{
        "is_required":1,
        "length":'',
        "requierd_message":"生年月日を選択してください。",
        "overflow_message":"",
        "type_error_message":""
    },
    "tall":{
        "is_required":0,
        "length":6,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "zip_code":{
        "is_required":0,
        "length":8,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "firstAddress":{
        "is_required":0,
        "length":50,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "building_name":{
        "is_required":0,
        "length":50,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "tel_number":{
        "is_required":0,
        "length":15,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "mobile_number":{
        "is_required":0,
        "length":15,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "mail_address":{
        "is_required":0,
        "length":255,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "move_reason":{
        "is_required":0,
        "length":100,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "move_destination":{
        "is_required":0,
        "length":50,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "notice":{
        "is_required":0,
        "length":100,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "dial_count_number":{
        "is_required":0,
        "length":9,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    },
    "comment":{
        "is_required":0,
        "length":100,
        "requierd_message":"",
        "overflow_message":"",
        "type_error_message":""
    }
  },
  "dial_insurance":{
    "insurer_number":{
        "is_required":1,
        "length":30,
        "requierd_message":"保険者番号を入力してください。",
        "overflow_message":"保険者番号は30文字以下で入力してください。",
        "type_error_message":""
    },
    "symbol":{
        "is_required":0,
        "length":30,
        "requierd_message":"記号を入力してください。",
        "overflow_message":"記号は30文字以下で入力してください。",
        "type_error_message":""
    },
    "bangou":{
        "is_required":0,
        "length":30,
        "requierd_message":"番号を入力してください。",
        "overflow_message":"番号は30文字以下で入力してください。",
        "type_error_message":""
    },
    "publicly_funded_treatment_recipient_number_1":{
        "is_required":0,
        "length":30,
        "requierd_message":"公費負担者番号Iを入力してください。",
        "overflow_message":"公費負担者番号Iは30文字以下で入力してください。",
        "type_error_message":""
    },
    "publicly_funded_treatment_recipient_number_2":{
        "is_required":0,
        "length":30,
        "requierd_message":"公費負担者番号IIを入力してください。",
        "overflow_message":"公費負担者番号IIは30文字以下で入力してください。",
        "type_error_message":""
    },
    "public_expenditure_recipient_number_1":{
        "is_required":0,
        "length":30,
        "requierd_message":"公費受給者番号Iを入力してください。",
        "overflow_message":"公費受給者番号Iは30文字以下で入力してください。",
        "type_error_message":""
    },
    "public_expenditure_recipient_number_2":{
        "is_required":0,
        "length":30,
        "requierd_message":"公費受給者番号IIを入力してください。",
        "overflow_message":"公費受給者番号IIは30文字以下で入力してください。",
        "type_error_message":""
    },
    "insurance_category_code":{
        "is_required":0,
        "requierd_message":"保険区分を選択してください。",
        "type_error_message":""
    },
    "issue_date":{
        "is_required":0,
        "requierd_message":"交付年月日を選択してください。",
        "type_error_message":""
    },
    "comment":{
        "is_required":0,
        "length":100,
        "requierd_message":"コメントを入力してください。",
        "overflow_message":"コメントは100文字以下で入力してください。",
        "type_error_message":""
    },
    "patient_burden_ratio":{
        "is_required":0,
        "length":2,
        "requierd_message":"患者負担割合を入力してください。",
        "overflow_message":"患者負担割合は2文字以下で入力してください。",
        "type_error_message":""
    },
    "insurance_card_category_code":{
        "is_required":0,
        "requierd_message":"保険証区分を選択してください。",
        "type_error_message":""
    },
  },
  "dial_emergency":{
    "name":{
            "is_required":1,
            "length":20,
            "requierd_message":"連絡先名を入力してください。",
            "overflow_message":"連絡先名は20文字以下で入力してください。",
            "type_error_message":""
        },
        "relation":{
            "is_required":0,
            "length":10,
            "requierd_message":"",
            "overflow_message":"続柄は半角10文字以下で入力してください。",
            "type_error_message":""  
        },
        "address_1":{
            "is_required":0,
            "length":50,
            "requierd_message":"",
            "overflow_message":"住所は50文字以下で入力してください。",
            "type_error_message":""  
        },
        "address_2":{
            "is_required":0,
            "length":50,
            "requierd_message":"",
            "overflow_message":"住所は50文字以下で入力してください。",
            "type_error_message":""  
        },
        "phone_number_1_name":{
            "is_required":0,
            "length":20,
            "requierd_message":"",
            "overflow_message":"名称①は20文字以下で入力してください。",
            "type_error_message":""  
        },
        "phone_number_1":{
            "is_required":0,
            "length":15,
            "requierd_message":"",
            "overflow_message":"TEL①は15文字以下で入力してください。",
            "type_error_message":""  
        },
        "phone_number_2_name":{
            "is_required":0,
            "length":20,
            "requierd_message":"",
            "overflow_message":"名称②は20文字以下で入力してください。",
            "type_error_message":""  
        },
        "phone_number_2":{
            "is_required":0,
            "length":15,
            "requierd_message":"",
            "overflow_message":"TEL②は15文字以下で入力してください。",
            "type_error_message":""  
        },
        "note":{
            "is_required":0,
            "length":100,
            "requierd_message":"",
            "overflow_message":"備考は100文字以下で入力してください。",
            "type_error_message":""  
        }
  },
  "dial_family":{
    "relation":{
        "is_required":1,
        "length":"",
        "requierd_message":"続柄を選択してください。",
        "overflow_message":"",
        "type_error_message":""
    },
    "age":{
        "is_required":1,
        "length":3,
        "requierd_message":"年齢を入力してください。",
        "overflow_message":"年齢を3桁以下の数字で入力してください。",
        "type_error_message":""
    },
    "note":{
        "is_required":0,
        "length":7,
        "requierd_message":"",
        "overflow_message":"備考は全角7文字以内で入力してください。",
        "type_error_message":""
    }
  }
}

export default function () {
    let init_status = sessApi.getObject(CACHE_SESSIONNAMES.INIT_STATUS);
    let dial_patient_validate = init_status.dial_patient_validate;    
    let return_obj = patient_validate_default;
    if(dial_patient_validate !== undefined && dial_patient_validate != null && Object.keys(dial_patient_validate).length > 0){      
      Object.keys(dial_patient_validate).map(index=>{
        if (Object.keys(dial_patient_validate[index]).length > 0){
          Object.keys(dial_patient_validate[index]).map(sub_key => {
            return_obj[index][sub_key] = dial_patient_validate[index][sub_key];  
          });
        }
      });
    }
    return return_obj;
}