export default function() {
  this.setState({
    AUTHS: {},
    FEATURES: {},
    selectedDoctor: {
      code: 0,
      name: ""
    },
    medical_department_name: undefined,
    duties_department_name: undefined,
    department: {
      code: 0,
      name: ""
    },
    featureAuths: [],
    commonAuths: [],
    insuranceTypeList: [],
    consentedList: [],
    consentedInjectionList: [],
    consentedAllOrderList: [],
    patientsList: [],
    bookmarksList: [],
    linkHistoryList: [],
    diseaseList: [],
    staff_category: 1,
    needSelectDoctor: false,
    schVal: "",
    dateStatus: new Date(),
    departmentStatus: 0,
    currentPatient: 0,
    treatStatus: 2,
    pageStatus: 1,
    limitStatus: 20,
    page: 1,
    processing: false,
    stopGetHistory: false,
    hasUnconsentedConfirmed: false,
    $selectDoctor: this.selectDoctor,
    $updateDoctor: this.updateDoctor,
    $updateStaffCategory: this.updateStaffCategory,
    $updateDepartmentName: this.updateDepartmentName,
    $updateDepartment: this.updateDepartment,
    $updateMedicineChangeHistory: this.updateMedicineChangeHistory,
    $updateInsuranceTypeList: this.updateInsuranceTypeList,
    $updateConsentedList: this.updateConsentedList,
    $updateConsentedAllOrderList: this.updateConsentedAllOrderList,
    $updateAuths: this.updateAuths,
    $updateDateStatus: this.updateDateStatus,
    $updateDepartmentStatus: this.updateDepartmentStatus,
    $updateTreatStatus: this.updateTreatStatus,
    $canDoAction: this.canDoAction,
    $resetState: this.resetState,
    $updateScrollTop: this.updateScrollTop,
    $updatePageNumber: this.updatePageNumber,
    $updateProcessing: this.updateProcessing,
    $updateStopGetHistory: this.updateStopGetHistory,
    $getMedicineChangeHistory: this.getMedicineChangeHistory,
    $updateBookmarksList: this.updateBookmarksList,
    $updateLinkHistoryList: this.updateLinkHistoryList,
    $screenCapture: this.screenCapture
  });
}
